### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by LeoVihera** [nkoiv/mists#1]
Projekti on huomattavan kokoinen ja siihen perehtyminen vei aika paljon aikaa, hyvä ja selkeä luokkakaavio auttoi kuitenkin paljon. Myös sekvenssikaaviot olivat ainakin niin selkeitä, kun ruutupaperille nyt saa piirrettyä ja kuvat olivat mukava lisä. En valitettavasti ehtinyt paljoa kokeilla itse pelin pelaamista, sillä minulla ei ollut varsinaista konetta paljoa käytössä, myöskin ajan puutteen vuoksi en kaikkiin luokkiin ehtinyt tarkasti perehtyä. Luokat on jaettu pakkauksiin, joilla on kaikilla selkeä käyttötarkoitus. Samoin luokkien käyttötarkoitukset ovat selkeitä. Jotkut metodit vaikuttivat ehkä turhan pitkiltä, vaikken tiedä selkeyttäisikö erityinen pilkkominen mitään (esimerkiksi Location luokan renderissä tai varsinkin MapGeneratorin metodeissa on aika paljon iffiä ja foria mitä ehkä voisi laittaa omiksi pienemmiksi metodeiksi). JavaDocit ja Kommentointi myös auttoi luettavuutta, vaikkei sitä ymmärrettävästi ihan kaikkialla ollukkaan jaksettu tehdä. Myös ToDo-huomautukset helpottivat tajuamaan, mitä vielä oli kesken. Hieno projekti!

**Comment by nkoiv** [comment]
Erittäin hyvä pointti noiden pitkien metodien kanssa.
Palastelin Locationin Renderin ehdotuksesi mukaisesti ja vilkaisen muutkin läpi, jos olisi eroteltavaa.
Location render() kutsuu nyt seuraavat:
* renderMap()
* renderMobs()
* renderStructureExtras()
* renderEffects()
